language: node_js

node_js:
  - '6.1'

sudo: false

env:
  - workerCount=3

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - npm test